# Default values for webcharts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
revisionHistoryLimit: 10 
containerPort: 4000
namespace: trado
appName: frontend

image:
  repository: registry.digitalocean.com/tramatch-registry/trado-fe
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations: 
  kompose:
    cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml -o prod/v2
    version: 1.21.0 (992df58d8)
    
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000



service:
  type: ClusterIP
  port: 80


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


nodeSelector: {}

tolerations: []

affinity: {}
